---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: nginxapp
  labels:
    app: nginx
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: nginx
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: realtimeapp
  labels:
    app: argocd-demo
spec:
  selector:
    matchLabels:
      app: argocd-demo
  replicas: 5
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
      - name: realtimeapp
        image: nginx
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8080
  strategy:
    canary:
      stableService: argocd-demo-stable
      canaryService: argocd-demo-canary
      #trafficRouting:
        #nginx:
          #stableIngress: argocd-demo-ingress
      steps:
      - setWeight: 50
      - pause: {}
---
apiVersion: v1
kind: Service
metadata:
  name: realtimeapp-stable
  labels:
    app: realtime
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: argocd-demo
---
apiVersion: v1
kind: Service
metadata:
  name: realtimeapp-canary
  labels:
    app: argocd-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: argocd-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: realtimeapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
spec:
  rules:
  - host: real.baeke.info
    http:
      paths:
      - path: /
        backend:
          serviceName: realtimeapp-stable
          servicePort: 80
